scss_files: 'app/assets/stylesheets/**/*.scss'

linters:
  Comment:
    enabled: false

  SelectorFormat:
    enabled: false

  SelectorDepth:
    enabled: false

  NestingDepth:
    enabled: false

  PlaceholderInExtend:
    enabled: false

  NameFormat:
    enabled: false

